### ISSUE TITLE
Add a JMH testsuite

### ISSUE THREAD

**Issue by roookeee** [roookeee/datus#23]
datus was just integrated [here](https://github.com/arey/java-object-mapper-benchmark) but the main repository could use some fancy images + benchmark statistics itself. The benchmark should focus on other mapping frameworks that don't use code generation but we should definitely mention those that do and how they compare to datus perf

**Comment by roookeee** [comment]
On second thought: Maybe just benchmark datus in this repositories JMH suite and reference the above linked benchmark, I don't really want to maintain third party mapper implementations

**Comment by roookeee** [comment]
@arey: How would you like to be referenced for this? I am loosly basing my benchmark suite on [yours](https://github.com/arey/java-object-mapper-benchmark), is [this](https://github.com/roookeee/datus/commit/788e5f28fb4a3ee502ecc0e8606f3c07b884c46a) okay? (I have a comment above the benchmark class)

**Comment by arey** [comment]
No problem @roookeee. If you want, you may reference the repo in the javadoc.

**Comment by roookeee** [comment]
Alright, will leave a reference to your repository in all files I have included :)

**Comment by roookeee** [comment]
Merged
