### ISSUE TITLE
source to destination conversion.

### ISSUE THREAD

**Issue by FuncGuy** [roookeee/datus#26]
Hi,
What if i want to convert a property from source byte to destination string this future is currently supported by map struct.

**Comment by roookeee** [comment]
Hi FuncGuy,

this is quite easy to achieve with *datus*: `.from(SomeObject::getBytes).map(bytes -> new String(bytes, Charsets.UTF_8).to(SomeOtherObject::setSomeString)`. Roughly speaking *datus* works just like `Stream`, you map your values until the desired output is reached an then end with a `to`.

Hope this helps,
roookeee

**Comment by FuncGuy** [comment]
got it

**Comment by FuncGuy** [comment]
any task that is available to work on?

**Comment by FuncGuy** [comment]
I am thinking to write conversion classes on calling these methods no need to write external mapping methods.. what is your opinion on this

**Comment by roookeee** [comment]
As I understand it you want to add some sort of utility functions? Where would you add them? All of datus components are highly generic so they dont make a good fit for your string specific proposal. As a rule of thumb: would your addition be good to include for the stream API of java? If not I dont think it would fit datus either. 

P. S. I have infrequent access to the web at the moment,  sorry for the delay

**Comment by roookeee** [comment]
There are no other open issues /enhancements at the moment besides some boring documentation tickets I will have to face :)  sorry

**Comment by roookeee** [comment]
Will close this issue as I feel like we resolved your question :)  feel free to comment if you think otherwise
