### ISSUE TITLE
Do we need  map all the fields ?

### ISSUE THREAD

**Issue by hb-0** [roookeee/datus#40]
It can be painful to map all the fields. Why do we need to map them even when the names are the same?

**Comment by roookeee** [comment]
There are other mapping frameworks that provide the feature you are asking for.
Sadly datus cannot provide this as it would require reflection which would break configuration-less GraalVM compatability which is one of the goals of datus :)

Take a look at MapStruct or [some other mapping framework](https://github.com/arey/java-object-mapper-benchmark) if the automatic mapping is a key feature for you.
